services:
  codeserver:
    image: ghcr.io/yourusername/codeserver:latest
    container_name: codeserver
    environment:
      - PASSWORD=password
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/home/coder/project
    restart: unless-stopped
